-- Create table roles
CREATE TABLE IF NOT EXISTS roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR
);

-- Create table users_roles (for 'many to many' relationship users and roles)
CREATE TABLE IF NOT EXISTS users_roles
(
    id BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT ,
    role_id BIGINT,
    constraint users_fk foreign key (user_id) references users (id),
    constraint roles_fk foreign key (role_id) references roles (id)
    );

--Insert data
INSERT INTO roles
VALUES
    (1, 'EDITOR'),
    (2, 'USER'),
    (3, 'ADMIN');

INSERT INTO users_roles (user_id, role_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 2),
    (3, 3);
